# Next Gen UI Configuration for Openshift MCP
# 1. yaml transformation for all
---
input_data_json_wrapping: true
unsupported_components: true

data_types:
  namespaces_list:
    data_transformer: fwctable
    components:
      - component: table
        configuration:
          title: Namespaces
          fields:
            - name: Name
              data_path: $[*].NAME
            - name: Status
              data_path: $[*].STATUS
            - name: Age
              data_path: $[*].AGE
            # - name: Labels
            #   data_path: $[*].LABELS
  projects_list:
    data_transformer: fwctable
  events_list:
    data_transformer: fwctable
  pods_get:
    data_transformer: yaml
  pods_list:
    data_transformer: fwctable
  pods_list_in_namespace:
    data_transformer: fwctable
    components:
      - component: table
        configuration:
          title: Pods
          fields:
            - name: Name
              data_path: $[*].NAME
            - name: Status
              data_path: $[*].STATUS
            - name: Ready
              data_path: $[*].READY
            - name: Age
              data_path: $[*].AGE
            - name: IP
              data_path: $[*].IP
            - name: Node
              data_path: $[*].NODE

  # returning CSV data!!!
  pods_log:
    data_transformer: noop
    components:
      - component: log
  # pods_top:
  #   data_transformer: yaml
  resources_list:
    data_transformer: fwctable
